### ISSUE TITLE
Initial Data Sync Fails after Typescript Refactor Update

### ISSUE THREAD

**Issue by billvsd** [pkmnct/robinhood-mint-sync-chrome#22]
I updated the extension and deleted the existing collectible account in Mint created by the previous version. I ran the Setup function in the new script and it created 4 Robinhood accounts in Mint (Cash, Crypto, Other, Stocks). The "Setup complete! Initiating Sync" appears and it opens a tab that has the "Syncing Mint and Robinhood... This window will automatically close when the sync is complete" overlay, but it gets stuck at that point and never syncs the data nor does the syncing tab ever close. Opening the Mint overview page shows the message "You have not yet performed a sync on this device. You must run an initial setup" where the same issue persists.

**Comment by pkmnct** [comment]
Could you check your Mint properties page, and ensure there are no properties named "Robinhood Account"? It is possible if you used the extension on multiple computers that more than one property was added.

Which tab gets stuck? Is it a Mint or Robinhood tab, and what is the URL?

**Comment by billvsd** [comment]
I had to delete the "Robinhood Account" from Mint after the Typescript Refactor, and there are currently no accounts with that name in Mint. After I updated the Chrome extension, the overview page said I had to delete that account which I did. After I deleted the "Robinhood Account" from Mint, I ran the Setup function which created 4 accounts (named "Robinhood Crypto," "Robinhood Other," "Robinhood Cash," and "Robinhood Stocks").

I have only used this extension on one computer.

When I click Setup, it opens a new tab (mint.intuit.com/settings.event?filter=property&setupRobinhood=true), then the URL in the background tab opens robinhood.com/account?syncMint=true and then the URL mint.intuit.com/settings.event?filter=property&addRobinhood=true which is where it gets stuck at.

**Comment by pkmnct** [comment]
When it gets stuck, are you able to see any of the Robinhood properties in the background? Does it try to fill them in?

**Comment by manoj-vk** [comment]
I also have the same issue. In my case, I see Robinhood properties updated in the background

**Comment by pkmnct** [comment]
I've released an update, 3.1.0, that should resolve this issue. There was a race condition in the save callback on the Mint update page. Please re-open this issue if you continue to have trouble after updating to 3.1.0.

**Comment by manoj-vk** [comment]
Still the same issue. I also deleted properties, reinstalled extension, but same result

**Comment by billvsd** [comment]
@pkmnct thanks for the update, but unfortunately the issue still persists. With the new debug mode on, I see this error in the console:

Error in event handler: TypeError: Error in invocation of tabs.sendMessage(integer tabId, any message, optional object options, optional function responseCallback): No matching signature.
    at Object.mint-property-setup-complete (chrome-extension://[extensionid]/js/background/main.js:1:2940)
    at chrome-extension://[extensionid]/js/background/main.js:1:5317

**Comment by pkmnct** [comment]
To help me better understand what is happening, please attach logs as follows:
1. If you have debug mode enabled already, skip to 6
2. Go to chrome://extensions/
3. Find Robinhood Mint Sync for Chrome
4. Click Details
5. Click Extension Options
6. Check the box to enable Debug Mode
7. Return to chrome://extensions/ (Go back to the listing)
8. Enable Developer Mode in the top-right of that page
9. Find Robinhood Mint Sync for Chrome
10. Turn it off and then back on.
11. Click the _background page_ link (Inspect views)
12. Click on the Console tab of your developer tools
13. In another window, initiate a sync. The tabs that would normally close will remain open and contain additional logs. I will have you check those in a moment.
14. Return to the developer tool/console window. Ensure the output does not contain any personal data (it should not on this screen)
15. Copy the output and paste it in a comment below (it should look similar to the example)

Example:
```
[Background](Main) initialized
[Background](Update/Install Listener) initialized
[Background](Browser Action) initialized
[Background](Main) mint-opened event
[Background](Main) robinhood-portfolio-scraped event
[Background](Main) waiting for Mint tab to load
[Background](Main) Mint tab loaded
[Background](Main) mint-sync-complete event
```

16. Find the tab that it normally gets stuck on.
17. Review the log, and attach any lines that contain "Robinhood Mint Sync" (make sure to exclude any personal information)

Example:
```
Robinhood Mint Sync - [Content](Mint - Properties - Update) initialized
Robinhood Mint Sync - [Content](Mint - Triangle Fix) initialized
Robinhood Mint Sync - [Content](Mint - Properties - Update) Waiting for Property Tab View to load

Robinhood Mint Sync - [Content](Mint - Properties - Update) Property Tab View loaded.
Robinhood Mint Sync - [Content](Mint - Properties - Update) Attempting to set Cash to <REMOVED>
Robinhood Mint Sync - [Content](Mint - Properties - Update) Found Cash input, setting amount
Robinhood Mint Sync - [Content](Mint - Properties - Update) Attempting to set Crypto to <REMOVED>
Robinhood Mint Sync - [Content](Mint - Properties - Update) Found Crypto input, setting amount
Robinhood Mint Sync - [Content](Mint - Properties - Update) Attempting to set Stocks to <REMOVED>
Robinhood Mint Sync - [Content](Mint - Properties - Update) Found Stocks input, setting amount
Robinhood Mint Sync - [Content](Mint - Properties - Update) Attempting to set Other to 0
Robinhood Mint Sync - [Content](Mint - Properties - Update) Found Other input, setting amount
Robinhood Mint Sync - [Content](Mint - Properties - Update) Fields updated. Attempting to save.
5Robinhood Mint Sync - [Content](Mint - Properties - Update) Clicking save
```

**Comment by billvsd** [comment]
I removed all Robinhood properties from Mint, uninstalled, and reinstalled the Chrome extension. Here are the background console logs. The errors fire off in rapid succession. 
[mogflmdandlpjobbddhopcggkjoggpdo-1610867289529.log](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825690/mogflmdandlpjobbddhopcggkjoggpdo-1610867289529.log)

**Comment by pkmnct** [comment]
@billvsd That error seems to indicate that the Mint update tab is never even opened. Do you see a tab with the url `https://mint.intuit.com/settings.event?filter=property&addRobinhood=true` open after the Robinhood tab?

**Comment by billvsd** [comment]
@pkmnct when I click **Set up** it opens and closes a tab with this URL https://mint.intuit.com/settings.event?filter=property&setupRobinhood=true

Then it opens another tab, first going to https://robinhood.com/account?syncMint=true and then https://mint.intuit.com/settings.event?filter=property&addRobinhood=true and this tab does not close like the first one

**Comment by pkmnct** [comment]
If the tabs are not remaining open (closing themselves) then debug mode is not fully enabled. Try toggling the extension off and back on (not uninstall/reinstall, just disable/enable) after enabling debug mode. Check if there is any additional logging in the Inspect views - background page. There should be some messages about events being fired (there may still be errors below those)

**Comment by billvsd** [comment]
@pkmnct sorry, after uninstalling and reinstalling I forgot to turn debugging back on. Here is the log file with debugging on again. After it says Tab opener must be in same window as the updated tab, it then enters an error loop in main.ts at line 60 and it appears that tab.id isn't defined. 
`chrome.tabs.get(tab.id, (tab) => {`

[mogflmdandlpjobbddhopcggkjoggpdo-1610869722160.log](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825708/mogflmdandlpjobbddhopcggkjoggpdo-1610869722160.log)

**Comment by billvsd** [comment]
![consolelog](https://user-images.githubusercontent.com/2430297/104834750-5a478380-5856-11eb-8dfd-58af97b9d42a.png)

**Comment by pkmnct** [comment]
@billvsd Ah, I think I may have found the issue. Would you be able to test the fix since I can't recreate it on my machine?

Here's a pre-compiled copy of [the changes](https://github.com/pkmnct/robinhood-mint-sync-chrome/compare/fix-tab-issue):
[robinhood-mint-sync-chrome@3.1.1.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825715/robinhood-mint-sync-chrome%403.1.1.zip)

The attempted fix is to open the tab from the initial Mint Overview tab instead of the Robinhood tab. There is also a fix for that potential endless loop should something go wrong.

You can load this as follows:
1. Disable the main install of Robinhood Mint Sync.
2. Extract the attached zip to a folder.
3. Open the Chrome Extensions Page (Chrome Menu > More Tools > Extensions).
4. Turn on the Developer Mode switch on the top-right of the page.
5. Choose the _Load unpacked_ button at the top and navigate to the folder you extracted to.

Alternatively, if you have familiarity with npm, you can follow  the [_Developer Use_](https://github.com/pkmnct/robinhood-mint-sync-chrome#developer-use) section of the guide with the `fix-tab-issue` branch.

**Comment by billvsd** [comment]
Sure thing. It looks like with that it is still throwing the Unchecked runtim.lastError: Tab opener must be in the same window as the updated tab but the following  Cannot read property of 'id' of undefined at main.ts:60 isn't thrown. 
![consolelog](https://user-images.githubusercontent.com/2430297/104835158-7d276700-5859-11eb-8c07-a03d11588d7c.png)

**Comment by pkmnct** [comment]
Hmm, seems to have stopped at a different spot this time. Try reloading your Mint Overview page. Since it hit the `mint-property-setup-complete` event, it should attempt to initiate a sync the next time that Mint page loads.

**Comment by billvsd** [comment]
Turned debuggin on, turned extension off then on, and reloaded mint Overview page. Here is the console log:
![consolelog](https://user-images.githubusercontent.com/2430297/104835829-16587c80-585e-11eb-8d53-e7bfb3aabdb3.png)

**Comment by pkmnct** [comment]
Well, the `openerTabId` should not be needed. I'll try removing it just to see if that can give us anything else to work with. I've added some additional logging to that event as well. Give this one a try:

[robinhood-mint-sync-chrome@3.1.1.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825773/robinhood-mint-sync-chrome%403.1.1.zip)

Thank you for your patience and willingness to help track down this issue.

**Comment by billvsd** [comment]
No problem at all. Thank you for the extension. Tracking my Robinhood balances in Mint is very helpful!

With this latest update, when not in debug mode it appears to get stuck on the "Mint > Settings" tab (and it does not close, it just remains open) https://mint.intuit.com/settings.event?filter=property&addRobinhood=true

With debug mode on, it is no longer throwing an error but appears to stop at "Mint tab loaded"
![consolelog](https://user-images.githubusercontent.com/2430297/104836215-2e7dcb00-5861-11eb-8c5c-edecc222e373.png)

**Comment by pkmnct** [comment]
That's a good sign. Could you check the console on that Mint page again?

**Comment by billvsd** [comment]
Here are just the errors from the console on the Mint page (https://mint.intuit.com/settings.event?filter=property&addRobinhood=true). Let me know if you need Verbose / Info / Warning levels of logging.
![consolelog](https://user-images.githubusercontent.com/2430297/104836408-a993b100-5862-11eb-8e2e-639fdb7169df.png)

**Comment by pkmnct** [comment]
Those all seem to be related to an ad/tracking blocker. I don’t see any messages related to this extension. Do you have Debug Mode turned on?

You should, at the very least, see an initialization message from the extension towards the top of the log. Do you get the extension overlay on that page?

**Comment by billvsd** [comment]
Yeah, that was just error-level logs. It is showing the overlay. 
![overlay](https://user-images.githubusercontent.com/2430297/104836702-97b30d80-5864-11eb-9e3d-d84c43314e57.png)

Here are the full log files. It appears to be filling in the account values, but not getting actually submitting or saving them and it gets stuck with the overlay. 
[mint.intuit.com-1610876133946.log](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5825822/mint.intuit.com-1610876133946.log)

**Comment by pkmnct** [comment]
From that log, it looks like it has trouble setting the "Robinhood Other" value. I found a possible race condition where it may try to set that before the input has loaded. Here's that attempted fix:

[robinhood-mint-sync-chrome@3.1.1.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5826567/robinhood-mint-sync-chrome%403.1.1.zip)

**Comment by manoj-vk** [comment]
The process appears to be complete (i.e it is closing the second tab and also showing the Sync complete confirmation message). But I don't see the balance reflected in the Mint property after reloading the screen.

**Comment by pkmnct** [comment]
@manoj-vk Could you enable Debug Mode for the extension and check the logs on the Mint update page? It sounds like perhaps it didn't receive the data from Robinhood. The logs should show what value it is attempting to set. If they all show 0, it is possible the Robinhood scrape is failing for you.

**Comment by billvsd** [comment]
@pkmnct here is a screenshot of the background console logs with the most recent update. It appears to complete the sync, but the balances remain at $0.00.
![consolelog](https://user-images.githubusercontent.com/2430297/104854271-990f2500-58ba-11eb-8875-af713890a3b7.png)


Here at the console logs from the Mint > Settings tab. There are actually two "Mint > Settings" tabs that are open both with the same logs. Looking at the page under the overlay, all of the values are zero. It appears that those aren't being filled in
[mint.intuit.com-1610912896531.log](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5826698/mint.intuit.com-1610912896531.log)

![overlay](https://user-images.githubusercontent.com/2430297/104854273-9dd3d900-58ba-11eb-89bf-8af04bf14bbe.png)

**Comment by billvsd** [comment]
I don't see the Collectible cards for the Robinhood accounts expand to show their values and the save button. I'm not sure if that has to happen but I suspect that could be the current issue. Feels like we're close! Thanks again.

**Comment by superpowered** [comment]
https://github.com/pkmnct/robinhood-mint-sync-chrome/pull/25 This should fix the issue.
It has to do with a false positive from an auto updating property.

**Comment by pkmnct** [comment]
@superpowered I've incorporated that bug fix (but not yet the fallback if the element is never found) into the `fix-tab-issue` branch, which contains some other bug fixes and enhancements. Feel free to test that branch out and following the  [_Developer Use_](https://github.com/pkmnct/robinhood-mint-sync-chrome#developer-use) section of the guide, or by using the pre-compiled version attached:

[robinhood-mint-sync-chrome@3.1.1.zip](https://github.com/pkmnct/robinhood-mint-sync-chrome/files/5826885/robinhood-mint-sync-chrome%403.1.1.zip)

@billvsd You can test this version too, to ensure your issue is resolved

**Comment by superpowered** [comment]
Seems to be fixed with 3.1.1 on my end, (including now correctly closing the extra settings tab, which was an issue that I was still seeing on my PR locally)

**Comment by manoj-vk** [comment]
Seem to be fixed. I don't have money in all categories, but it is setting values for what I have. Thank you so much

**Comment by pkmnct** [comment]
Great news! I'll get this pushed to the Chrome Web Store ASAP!

**Comment by billvsd** [comment]
@pkmnct thank you so much for resolving the issue. I can also confirm that it is now working after the last update. Great job on this extension!
